### ISSUE TITLE
DOUBLE Content resp. LINK on https://sabbath-school.adventech.io/de/2016-04/08

### ISSUE THREAD

**Issue by jGAtGithubCom** [Adventech/adventech.io#8]
The link in IV / 2016 of
November 12th ('Samstag, November 12') and November 14th ('Montag, November 14') are indentical, the content too:
https://sabbath-school.adventech.io/de/2016-04/08/unschuldiges-blut/
So I'm missing the content of one day.
Could you fix this problem?
Thanks a lot,
best reagrds

**Comment by gocursor** [comment]
The same problem appears in Slovenian translation for the current week: https://sabbath-school.adventech.io/sl/2021-02/07/zaveza-na-sinaju/

The problem seems to be that the title for Saturday (Sabbath) and Tuesday is the same (is our case "zaveza-na-sinaju" and in German case above "unschuldiges-blut") and your "website generator" does not produce two different pages in this case but overrides the Saturday content with the Tuesday content.
